typography_spectrum: 0.36128
color:
  brandColors:
    - '#000000'
    - '#dbd7d4'
    - '#979394'
    - '#1f5e81'
    - '#df9c4b'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0.25
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.74374
analytics:
  google: null
  facebook: null
  twitter: null
name: Julio Cafe
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Gallery
    id: e5cd1b0f-ec84-4800-8778-1557285f3a67
    type: content
favicon: null
title: Fitzroy Cafe & Function Venue
description: Tagline goes here...
purpose: []
