name: Julio Cafe
favicon: null
layout_spectrum: 1
typography_spectrum: 0.7975787029135972
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#dbd7d4'
    - '#979394'
    - '#1f5e81'
    - '#df9c4b'
  brandStrength: 0.125
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
