name: Julio Cafe
favicon: null
layout_spectrum: 0.24471
typography_spectrum: 0.43835
title: 'Fitzroy Cafe & Function Venue'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#dbd7d4'
    - '#979394'
    - '#1f5e81'
    - '#df9c4b'
  brandStrength: 0
  lightness: 0.75
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
